### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_all_memberproperties'

### ISSUE THREAD

**Issue by rafaeltcc** [collective/Products.EasyNewsletter#119]
Hi,
I have a Plone 5.07 site. and 3.beta Easynewsletter. I installed the product, created a draft, when sending got following traceback:

```

Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module Products.EasyNewsletter.browser.issue, line 57, in send_issue
    Module Products.EasyNewsletter.browser.issue, line 73, in send_issue_immediately
    Module Products.EasyNewsletter.content.ENLIssue, line 415, in send
    Module Products.EasyNewsletter.content.ENLIssue, line 302, in _send_recipients
    Module Products.EasyNewsletter.content.ENLIssue, line 542, in get_plone_subscribers

AttributeError: 'NoneType' object has no attribute 'get_all_memberproperties'
```

When I try to send a test mail I get...

Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module Products.EasyNewsletter.browser.issue, line 38, in send_issue
    Module Products.EasyNewsletter.content.ENLIssue, line 415, in send
    Module Products.EasyNewsletter.content.ENLIssue, line 273, in _send_recipients

AttributeError: 'str' object has no attribute 'get'

**Comment by MrTango** [comment]
can you please try the current master branch, I will make the next release soon.
And we fixed a lot meanwhile.

**Comment by MrTango** [comment]
closing this, feel free to reopen.
