### ISSUE TITLE
Question to subscribeable newsletters/channels and daily issues

### ISSUE THREAD

**Issue by petschki** [collective/Products.EasyNewsletter#120]
Hi! coming from Singing&Dancing's (which finally was statet dead here https://github.com/collective/collective.dancing/issues/29 by @pbauer) channels/digest subscriptions I'm searching for another way to implement this functionality into Plone.

So I tried to look at the daily-issue functionality in this package, but got stuck somehow:

- is there a simple subscription form view without using portlets?
- is there a possibility to subscribe to more than one newsletter at once?
- how does ENL handle new/changed content of collections when triggering daily/weekly?

I would be glad if someone can give me some pointers if this package is the right place to implement this?

**Comment by agitator** [comment]
> is there a simple subscription form view without using portlets?

I'm using a diazo rule to display the portlet content within a standard page, but would welcome a subscription view

> is there a possibility to subscribe to more than one newsletter at once?

No, only the dropddown to select one - there's no functionality yet to create the respecting user within every selected newsletter. I think the subscription process would have to be extended as well to not send out a confirmation mails for every newsletter a user subscribes to - imho there should be just one such mail

**Comment by MrTango** [comment]
It's currently not possible to subscribe to more then one newsletter, but I plan to add this functionality.
A form view witch show all existing Newsletters and allow one to subscribe or unsubscribe would be really nice and not hart to build. If you have some budget for this or time to develop this would be great.

**Comment by MrTango** [comment]
> how does ENL handle new/changed content of collections when triggering daily/weekly?

We just create a Newsletter issue every day/week/month and aggregate the content via referenced Plone Collections, so it's up to you how you configure your Collections. If nothing is found with the Collections no issue will be created. It's now also possible to trigger the daily_issue view with cron4plone.

If you have more ideas how we can improve this functionality let me know.
I did a lot of work recently to improve the Newsletter and the templates for the generation process.
For the future we plan to implement also a nice editor https://mosaico.io/ which will work much better for manual creation or fine tuning after aggregation.

**Comment by MrTango** [comment]
I added a ticket for the subscription form: https://github.com/collective/Products.EasyNewsletter/issues/121

**Comment by MrTango** [comment]
closing this, as there is nothing to do here.
