### ISSUE TITLE
reinstalling on plone5 removes previously installed items ...

### ISSUE THREAD

**Issue by zmijunkie** [collective/Products.EasyNewsletter#123]
Reinstalling a Product should not remove components installed before ... 
What helped me:

cd profiles/base
cp -pr * ../plone5

BTW: portal_atct.xml is missing/broken (Collection and image scales settings is missing) 
This prevents to make a snapshot using portal_setup to see what is going on ...

**Comment by MrTango** [comment]
what do you mean by "Reinstalling"? the usage of portal_quickinstaller to reinstall, is not recommanded at all anymore and will cause troubles. I just tested it and ended up having no EasyNewsletter resources anymore in portal/skins, which is strange. I'll probably not spent to much time now in the old version. Let's see if we can reproduce this in the new DX version of ENL and then handle it.

**Comment by MrTango** [comment]
closing this, feel free to reopen.
