### ISSUE TITLE
Attachment state of issues not updated on send

### ISSUE THREAD

**Issue by mul890** [collective/Products.EasyNewsletter#13]
After sending an issue for real (not test), the issue state will become 'sent'. However, the attachment states nog longer seem to be updated at the same time, and stay at 'internal draft'. This requires people receiving the newsletter to login before being able to view the attachment.

We are using version 2.6.1 of EasyNewsletter (with Plone 4.1.4). However, in a previous version (maybe 2.5.x?) it did work as expected. I browsed through the code at GitHub but could not find any change that could have caused this misbehavior.

**Comment by jensens** [comment]
file and image do no longer have an own workflow state. in any case if needed to do so I propose to set the state based on a custom subscriber.
