### ISSUE TITLE
Unsubsribe mails are getting tagged as spam

### ISSUE THREAD

**Issue by agitator** [collective/Products.EasyNewsletter#131]
Opposite to the subscribe confirmation mails, unsubscribe mails are getting tagged as spam, at least on one occasion here.

I think we should:
- add a bit more information/text inside this mail, right now it only says `Click here to unsubscribe and the unsubscribe link`
- add the site name to the mails subject

opinions?

**Comment by MrTango** [comment]
The text is comming from the newsletter object it self and can be changes there. Right now this is only a textLine field that we could think about to change. The Problem with just adding more text somewhere in code, is that we want it for different langugages.
Now one can at least put there own text in there.

**Comment by MrTango** [comment]
The subject is comming from the view, this could be changed.
