### ISSUE TITLE
Fail to install Easy.Newsletter via Plone Management Interface

### ISSUE THREAD

**Issue by hugodina** [collective/Products.EasyNewsletter#132]
Hi everyone,

EasyNewsletter fails to install via PMI. 
Products.EasyNewsletter 3.0.5
Plone 5.0.4 (5015) [unified installer]
CMF 2.2.10
Zope 2.13.24
Python 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
PIL 3.1.1 (Pillow)

Error message :
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.controlpanel.browser.quickinstaller, line 213, in __call__
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 686, in installProducts
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 603, in installProduct
   - __traceback_info__: ('Products.EasyNewsletter',)
  Module Products.GenericSetup.tool, line 379, in runAllImportStepsFromProfile
   - __traceback_info__: profile-Products.EasyNewsletter:default
  Module Products.GenericSetup.tool, line 1414, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1226, in _doRunImportStep
   - __traceback_info__: combine-bundles
  Module Products.CMFPlone.resources.exportimport.bundles, line 28, in combine
  Module Products.CMFPlone.resources.browser.combine, line 107, in combine_bundles
  Module Products.CMFPlone.resources.browser.combine, line 71, in write_js
  Module plone.resource.directory, line 154, in writeFile
  Module OFS.Image, line 139, in __init__
  Module OFS.Image, line 535, in _read_data
  Module StringIO, line 106, in seek
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 43924: ordinal not in range(128)

**Comment by MrTango** [comment]
I'll have a look at it this weekend, as I will make a new release soon anyway.

**Comment by MrTango** [comment]
One question, did you try the newest version of Plone 5.0.x?
please try with least 5.0.8

**Comment by hugodina** [comment]
Not yet, I'll...

Thanks

**Comment by MrTango** [comment]
I couldn't reproduce it on a Plone 5.0.8.
Please try with this version and reopen if you still see problems.

**Comment by hugodina** [comment]
I'm doing so and I come back soon... Thanks
