### ISSUE TITLE
Encoding of Welcome Mail always us-ascii

### ISSUE THREAD

**Issue by faucon** [collective/Products.EasyNewsletter#15]
Hi,

the welcome mail of EasyNewsletter (Version 2.6) is always encoded as:

Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

although the setting for my plone instance is "utf-8" (for default encoding in genreal and for email encoding, too)
and for this reason, german "umlauts" (äöu etc.) doesn't work.

Best,
Maximilian

**Comment by jensens** [comment]
fixed with #41
