### ISSUE TITLE
Store information about sent emails per issue

### ISSUE THREAD

**Issue by thomasmassmann** [collective/Products.EasyNewsletter#154]
It would be nice to store the information about successfully sent emails and failed ones per issue.
Currently the information is logged, but not available for further usage.

**Comment by MrTango** [comment]
As discussed, we should also use the info, for a retry send function.
Meaning, when someone forgot to select some subscribers or groups whe could correct the selection and send the issue again. A ReceiversPostSendingFilter could make sure that no receiver get the email twice.

**Comment by MrTango** [comment]
realted to #95

**Comment by thomasmassmann** [comment]
We use the branch currently in a customer project and so far it is working great, customer is happy.

Current status:
- store recipients information with send status as annotation on newsletter issue once sending is completed (to avoid too much writing during send process)
- new `IReceiversPostSendingFilter` adapter filters recipient who already got the email, so issue will be sent only to failed and new recipients
- statistics page, allowing to reset statistics (for sending all emails again)
- reset statistics when issue is transformed into master

Some bugfixes and enhancements required for this to work:
- set `cssutils` log to error instead of warning
- `IReceiversPostSendingFilter` subscriber call is moved from plone user and group behavior to send method to filter all recipients and not just plone users
- `IReceiversPostSendingFilter` is also checking for `INewsletterIssue` adapters (which we use here to filter successfully sent emails)

**Comment by thomasmassmann** [comment]
Released as 5.0.0b1.
