### ISSUE TITLE
Incorrect email regular expression

### ISSUE THREAD

**Issue by pabo3000** [collective/Products.EasyNewsletter#159]
An email address with a long top level domain leads to an error.

Example: bob@example.hamburg

The regular expression in the config.py lets only pass top level domains less or equal 6 chars.

**Comment by mck9** [comment]
email addresses should be checked with "validate_email" from "email_validator" module. Why is there an regexp?

**Comment by MrTango** [comment]
because this add-on is older than the email_validator and so is the regex ;).
But we could switch to it, PR welcome.

**Comment by mck9** [comment]
I am cleaning up old and not used code currently. I f come by I will make a PR for you.

**Comment by MrTango** [comment]
any news? I'll make a final release in the next days.
