### ISSUE TITLE
Unable to add subscriber portlet

### ISSUE THREAD

**Issue by richardtc** [collective/Products.EasyNewsletter#16]
I'm unable to insert a path to the newsletter when attempting to create a subscriber portlet. 

I click on the search button and nothing happens. Similarly, I enter a path and the field remains empty after clicking on search or apply.

System: Plone 4.1.5
EasyNewsletter: 2.6.7

**Comment by jensens** [comment]
probably fixed on master, but needs check

**Comment by agitator** [comment]
works with EasyNewsletter 3.x and Plone 4.3.4
