### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec 

### ISSUE THREAD

**Issue by richardtc** [collective/Products.EasyNewsletter#19]
Receive the following error on attempting to send draft newsletter.

Plone 4.1.5
EasyNewsletter: 2.6.11

We’re sorry, but there seems to be an error…

Here is the full error message:

Display traceback as text

Traceback (innermost last):

Module ZPublisher.Publish, line 126, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 46, in call_object
Module Products.EasyNewsletter.browser.issue, line 24, in send_issue
Module Products.EasyNewsletter.content.ENLIssue, line 323, in send
Module Products.EasyNewsletter.content.ENLIssue, line 271, in _exchange_relative_urls
Module HTMLParser, line 108, in feed
Module HTMLParser, line 142, in goahead
Module Products.EasyNewsletter.utils.ENLHTMLParser, line 62, in handle_data
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 115: ordinal not in range(128)

**Comment by jensens** [comment]
We can not verify this bug. If this is still valid please reopen and provide a recipe how to show up the bug .
