### ISSUE TITLE
CssUtils > 0.9.7 does not work with Plone 3 and Products.EasyNewsLetter

### ISSUE THREAD

**Issue by cleberjsantos** [collective/Products.EasyNewsletter#22]
It is necessary to pin **cssutils** to version **0.9.7** (either on versions.cfg or in your setup.py)

**Comment by jensens** [comment]
obsolete - no longer used.

**Comment by jensens** [comment]
i got it wrong, its used by stoneagehtml - but today version 1.0 works fine with latest stoneagehtml
