### ISSUE TITLE
[[UNSUBSCRIBE]] link doesn't get styled

### ISSUE THREAD

**Issue by petschki** [collective/Products.EasyNewsletter#26]
because the [[UNSUBSCRIBE]] is replaced with a link **after** the output_template is rendered, the link doesn't get individual template style definitions.

a possible solution for this would be to separate the replacement placeholders into [[UNSUBSCRIBE_LINK]] and [[UNSUBSCRIBE_TEXT]] and set the default_footer_text to

```
<p>-----------------------------------------------<br /><a href="[[UNSUBSCRIBE_LINK]]">[[UNSUBSCRIBE_TEXT]]</a></p>
```

otherwise we have to render the whole template for every recipient and this would decrease performance significantly, what do you think?

**Comment by jensens** [comment]
since this is now all done in one template before ``compactify`` this is not longer the case.
