### ISSUE TITLE
Error on sending content with images

### ISSUE THREAD

**Issue by djowett** [collective/Products.EasyNewsletter#29]
- LOW PRIORITY -

I get this error (with the latest source version) when trying to test send a newsletter.

Any clues?

Traceback (innermost last):

    Module ZPublisher.Publish, line 126, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 46, in call_object
    Module Products.EasyNewsletter.browser.issue, line 24, in send_issue
    Module Products.EasyNewsletter.content.ENLIssue, line 413, in send
    Module email.mime.image, line 46, in __init__
    Module email.encoders, line 45, in encode_base64
    Module email.encoders, line 31, in _bencode

AttributeError: __getitem__ 

Thanks if anyone can help,
Daniel

**Comment by jensens** [comment]
Logo in the default template is fetched with: ``<img src="logo.png" />``
Not sure if this is perfect.

**Comment by agitator** [comment]
```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.EasyNewsletter.browser.issue, line 51, in send_issue
  Module Products.EasyNewsletter.browser.issue, line 60, in send_issue_immediately
  Module Products.EasyNewsletter.content.ENLIssue, line 449, in send
  Module Products.EasyNewsletter.content.ENLIssue, line 520, in _get_issue_data
  Module Products.EasyNewsletter.content.ENLIssue, line 606, in _get_images_to_attach
  Module email.mime.image, line 41, in __init__
  Module imghdr, line 21, in what
  Module imghdr, line 37, in test_jpeg
TypeError: 'NamedBlobImage' object has no attribute '__getitem__'
```

happens if you add images to the content via the wysywig editor

**Comment by agitator** [comment]
fixed with https://github.com/collective/Products.EasyNewsletter/pull/72

please reopen if another problem appears
