### ISSUE TITLE
Plone-4.2.3 install fails with KeyError: u'profile-inqbus.plone.fastmemberproperties:uninstall'

### ISSUE THREAD

**Issue by ida** [collective/Products.EasyNewsletter#33]
2013-01-25 10:51:51 ERROR Zope.SiteErrorLog 1359107511.090.147377374917 http://example.com:8080/@@plone-addsite
Traceback (innermost last):
  Module ZPublisher.Publish, line 126, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 46, in call_object
  Module Products.CMFPlone.browser.admin, line 206, in __call__
  Module Products.CMFPlone.factory, line 102, in addPloneSite
  Module Products.GenericSetup.tool, line 350, in runAllImportStepsFromProfile
   - __traceback_info__: profile-Products.EasyNewsletter:uninstall
  Module Products.GenericSetup.tool, line 1073, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1056, in getProfileDependencyChain
  Module Products.GenericSetup.tool, line 1054, in getProfileDependencyChain
  Module Products.GenericSetup.tool, line 835, in getDependenciesForProfile
KeyError: u'profile-inqbus.plone.fastmemberproperties:uninstall'

**Comment by jensens** [comment]
check if this is still valid on master

**Comment by ida** [comment]
feel free to close, of my side
