### ISSUE TITLE
Use custom permissions for add ENL, add issue ...

### ISSUE THREAD

**Issue by djay** [collective/Products.EasyNewsletter#42]
A lot of the views are protected by ManagePortal which doesn't make much sense. None managers can create issues but not view the drafts after they made them. They can't send test messages or send an issue. etc

**Comment by MrTango** [comment]
What is the current state?
Please try out the current 3.0 release and update or close the issue.
The last question from @bglatt is more a feature request. By now one can't disallow add newletter if the user has the right to add content. But we could provide a special permission like Add EasyNewsletter and Modify EasyNewsletter

**Comment by MrTango** [comment]
@bglatt in case you still need this feature, please add an issue for that.

**Comment by MrTango** [comment]
Please test with the new Dexterity based version if it fit's your needs.
I'll close this issue for now, if you have more detailed reuirements based on the current version, please open a new issue.
