### ISSUE TITLE
sender email in "send" view not permanently saved is confusing

### ISSUE THREAD

**Issue by djay** [collective/Products.EasyNewsletter#45]
You can set the sender email address and name in the Issue send page, however this isn't permanently saved. This can lead to confusion. Users should be warned that this isn't saved, or it should save that information into the Issue object.

**Comment by jensens** [comment]
The default test email address is saved on the Newsletter itself. I dont think we should override this when saving this form, this would lead to further confusion.

**Comment by MrTango** [comment]
I agreen with jensens, there is no need to save this there.
This is just the send form und you can override this for exact that sending.
I never had the gues that it would saved there.
But @djay feel free to optimize the description text of the form if you like to make it more clear.

**Comment by djay** [comment]
The issue was badly worded. Fro memory it was more that it combines two.dialogs in one. It has both a save and a send. I will have another look
