### ISSUE TITLE
CI fails for Plone versions lower than 4.2

### ISSUE THREAD

**Issue by MrTango** [collective/Products.EasyNewsletter#49]
More information:

* Plone 4.1: https://travis-ci.org/collective/Products.EasyNewsletter/jobs/26741070
* Plone 4.0: https://travis-ci.org/collective/Products.EasyNewsletter/jobs/26741069

**Comment by agitator** [comment]
Support for 4.0 and 4.1 was dropped on master, targeting > 4.3 only
