### ISSUE TITLE
Easy newsletter icon

### ISSUE THREAD

**Issue by jeanferri** [collective/Products.EasyNewsletter#53]
I'm experencing an error because easynewsletter does'nt have an icon then the 'Add Item' Plone menu call the default icon document_icon.gif by acquisition what raises the attached error screen.

![easy-newsletter-error](https://cloud.githubusercontent.com/assets/719982/4325191/a54e170e-3f62-11e4-8119-7e75bf9b7ed7.png)

I made an icon for easy newsletter you can use, if you wish, based on http://fortawesome.github.io/Font-Awesome/icon/newspaper-o/ It's also attached here... ;-)

![newsletter_icon](https://cloud.githubusercontent.com/assets/719982/4325192/a5511fb2-3f62-11e4-8375-ad4e46626ac8.png)

Regards

**Comment by agitator** [comment]
updated with "old" style icons, at least for now https://github.com/collective/Products.EasyNewsletter/commit/7133a38b15d03a33513a97014af6cfbb6ab13f7e
