### ISSUE TITLE
error when trying to create a portlet Subscriber

### ISSUE THREAD

**Issue by FabrizioTolu** [collective/Products.EasyNewsletter#54]
I have tried to add an “Newsletter Subscriber” portlet but I have found this generic error:

......ERROR Zope.SiteErrorLog 1411466934.940.0230444063721 http:localhost:8080/ProvePlone/++contextportlets++plone.rightcolumn/+/portlets.Subscriber/@@formlib_validate_field
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 72, in mapply
  Module ZPublisher.Publish, line 53, in missing_name
  Module ZPublisher.HTTPResponse, line 741, in badRequestError
BadRequest:   <h2>Site Error</h2>
  <p>An error was encountered while publishing this resource.
  </p>
  <p><strong>Invalid request</strong></p>
  The parameter, <em>fname</em>, was omitted from the request.<p>Make sure to specify all required parameters, and try the request again.</p> 
................

**Comment by agitator** [comment]
works with EasyNewsletter 3.0 and Plone 4.3.4
