### ISSUE TITLE
Upgrade to new style collections support planned?

### ISSUE THREAD

**Issue by bglatt** [collective/Products.EasyNewsletter#56]
When adding collection criteria to a newsletter, it seems to me that this functionality is based on the old style collections. Would it make sense or are there plans to upgrade EasyNewsletter to new style collections in the future?

I use a third party addon named Reflecto, whose content type "Reflecto file" is recognized only with new style collections. Basically I can filter those items by type only with a new style collection, and not through EasyNewsletter or the old "topic" which give me an empty folder.

I'm using Plone 4.3.1 and EasyNewsletter 2.6.14

**Comment by jensens** [comment]
Given we work now with ``plone.app.contenttypes`` in Plone 5 by default this needs a check.
