### ISSUE TITLE
Female Salutation should be Mrs. instead of Ms.

### ISSUE THREAD

**Issue by agitator** [collective/Products.EasyNewsletter#57]
should be "Mrs. | Frau" and not "Ms. | Fräulein"

this would be a bigger change (subscription form and throughout the system) and most probably would need some fallback mechanisms for older installations

**Comment by djowett** [comment]
As I said in the related pull request comments:


Actually the generic feminine greeting **should** be "Ms" in English.
"Miss" is a single lady
"Mrs" is a married woman
"Ms" is used when you don't know (or they don't want you to know) whether they are married or not.

I know things may be different in German (and French), but please don't break this for us Brits!

**Comment by agitator** [comment]
fixed with https://github.com/collective/Products.EasyNewsletter/pull/60
