### ISSUE TITLE
Salutation should just use Lastname

### ISSUE THREAD

**Issue by agitator** [collective/Products.EasyNewsletter#58]
The salutation line now uses the full name of a person/member, 
afaik the salutation should just use the last name 

for example 
"Dear Mr. Meier" and not "Dear Mr. Martin Meier"
"Sehr geehrter Herr Meier" and not "Sehr geehrter Herr Martin Meier"
"Monsieur Meier" and not "Monsieur Martin Meier"

This would also mean we have to change the subscription form and subscriber type.

**Comment by djowett** [comment]
I agree this is currently too long, but please see also my comments in #37 - basically, most newsletters address me quite informally ("Dear Daniel"), none of this "Mr" stuff, so I think that should be an option at some point (or stay as an option if it's already there)

**Comment by agitator** [comment]
in my case, the client wants a formal salutation ...

seems an option "use formal salutation" for the newsletter itself would make sense
so either "Dear Daniel" or "Dear Mr Jowett"?

either way to make this possible, a split up of the field fullname and a migration step would be needed?

**Comment by agitator** [comment]
taking your comment into the discussion here  https://github.com/collective/Products.EasyNewsletter/pull/59#issuecomment-85121591 

in the project I'm working on, we use:
Dear Mr. Last name
Sehr geehrter Herr Nachname
Monsieur FR Nom

proposal informal salutations:
en "Dear [first_name]"
de "Hallo [first_name]"
fr "Bonjour [first_name]"

proposal formal salutations:
en "Dear [salutation] [first_name]"
de "Sehr geehrter [salutation] [first_name]"
fr "[salutation] [first_name]" 

further project specific cases could still be done with translation overrides

**Comment by djowett** [comment]
I think that's better than what we have at the moment, but please don't go just on my say so. Thoughts from others like @MrTango would be good!

**Comment by jensens** [comment]
Why not define the vocabulary more flexible as strings with placeholders instead of just device in formal and informal? I'am sure in other parts of the world there are again different ways to salutate.

**Comment by djowett** [comment]
@jensens I did wonder about something like that, but would it not be tricky if, like @agitator, you have to handle multiple languages on the same site?

**Comment by jensens** [comment]
i think you have to define it in either as a list of triples::

    ('male', 'en', 'Dear Mr. {givenname} {surname}'),
    ('male', 'de',  'Sehr geehrter Herr {surname}')
    ('female', ....)

or as a dict of dicts (from code easier to use).

    {'male': 
        {'en': 'Dear Mr. {givenname} {surname}', 
         'de': 'Sehr geehrter Herr {surname}'},
     'female': ....
    }

simplest widget would be a lines delimited by ```|``` in the style:
 
    male|en|Dear Mr. {givenname} {surname}

I suppose more convenient would be a datagridwidget.

**Comment by djowett** [comment]
+1 to that.
The dict of dicts model also helps avoid duplicate rows (e.g. for  'male', 'de')

**Comment by agitator** [comment]
replaced with https://github.com/collective/Products.EasyNewsletter/issues/75
