### ISSUE TITLE
Images not included in email

### ISSUE THREAD

**Issue by wimbou** [collective/Products.EasyNewsletter#6]
Hi,

When sending a newsletter edition that contains images, on of the images are shown either in thunderbird or GMail. Looking at the source in thunderbird I """<p><img alt=3D"This is the description of the image" class=3D"image-inl=
ine" src=3D"cid:image_0" /></p>""" makes me think an attachment with the image is missing. In the rendered source of GMail I can see """"<p><img alt="This is the description of the image"></p>"""

Using Plone 4.0.8 on Zope 2.12.19. The EasyNewsletter tests gave no error(s).

Any idea what could be causing the missing images in the email?

**Comment by jensens** [comment]
should be fixed with #43
