### ISSUE TITLE
Newsletter Template(s) from Filesystem 

### ISSUE THREAD

**Issue by agitator** [collective/Products.EasyNewsletter#63]
- allow multiple newsletter-mail-templates from filesystem 
- allow customization ttw via static resource folder in zmi
- configuration of available templates on newsletter container (availabiltiy, order)
- selection of newsletter-mail-tempate on nl-issue

**Comment by MrTango** [comment]
Currently we have this with skinsfolder templates, so I'l close this.
If someone wants to modernice this with a working version of static resource folder including customization story, I'm open for it.
