### ISSUE TITLE
Plone 5 version

### ISSUE THREAD

**Issue by ebrehault** [collective/Products.EasyNewsletter#66]
For your information, I have initialized a Plone 5 branch https://github.com/collective/Products.EasyNewsletter/tree/plone5

Note: initially I thought I could keep the code compliant with both Plone 4 and Plone 5, but I am affraid it is too heavy.

**Comment by agitator** [comment]
what are the main changes that won't work with p4?
do you plan to replace at types with dx as well?

**Comment by ebrehault** [comment]
Changes are not that big, but we have to change all the templates to add plone.protect authenticator token in all links and I do not see a clean way to maintain several versions of the templates.

I haven't planned to migrate it to Dexterity, I just make the necessary fixes to make it work the way it is (by the way, I had to fix stuffs in Products.ATContentTypes, Products.Archetypes, and archetypes.multilingual, so you will need to checkout their GitHub master branch if you want to run ENL on Plone 5. I will commit a proper buildout soon.)

**Comment by agitator** [comment]
any chance that we make those template additions conditional?

**Comment by ebrehault** [comment]
Maybe.
We might create a plone5_skins folder and try to declare a new skin that would be enabled only for Plone 5.

**Comment by jensens** [comment]
branch was merged and master targets 4.3, 5.0, 5.1 - still work left, but I close this one in favor of more detailed problem descriptions.
