### ISSUE TITLE
Extra Products.Newsletter folder with only some translation files

### ISSUE THREAD

**Issue by fredvd** [collective/Products.EasyNewsletter#70]
The add'on contains an extra "Products.EasyNewsletter" folder in the root of the project with only a locals folder with german translations. Is this necessary, or has there bee a merge/typo while updating translations?

**Comment by fredvd** [comment]
@mrtango the commit is 3678ec46b549c77e2172022bc0cc0bd05a4aba21 , done on may 11th.

**Comment by agitator** [comment]
@mrtango what do you think?

**Comment by MrTango** [comment]
maybe i did something wrong, if it is not used just delete it ;)

**Comment by agitator** [comment]
removed https://github.com/collective/Products.EasyNewsletter/commit/2326deabe30828126fdc1d1b2406cd86abe67417
