### ISSUE TITLE
Allow the use of placeholders within getText

### ISSUE THREAD

**Issue by agitator** [collective/Products.EasyNewsletter#75]
Shall we move to (or allow) string placeholders for the injection of personalized parts within the main content area?
for example [[HEADER]]  go get the contents of "context/getHeader"

implications? opinions?

**Comment by MrTango** [comment]
Could be usefull. I wounder if we should switch the placeholders in general to the same format as in Plone content rules placeholders. So people can use it the same way.

**Comment by agitator** [comment]
what is the actual placeholder format for Plone content rules?

**Comment by MrTango** [comment]
i  mean for example the placeholders in the email notification action of the content rules.
Just try to add a rule for email notification, then you will get a list of all placeholders.

**Comment by petschki** [comment]
:+1: see here: https://github.com/plone/plone.stringinterp ... this is where the email action from plone.app.contentrules gets its interpolation

**Comment by jensens** [comment]
"mit Kanonen auf Spatzen schießen"
https://translate.google.at/?oe=utf-8&ie=UTF-8&hl=de&client=tw-ob#de/en/mit%20Kanonen%20auf%20Spatzen%20schie%C3%9Fen

**Comment by agitator** [comment]
I like the syntax "Here is the title: ${title}", but ... 
For the newsletter, at least for now, we would just need a replacement for "Header" and "Footer".
Almost none of the existing "Replacement" within plone.stringinterp are useless in the context of a newsletter.

also i think this is kind of an overusage of zca for such a simple usecase

**Comment by agitator** [comment]
planned extension:

we'll add an event within _personalize_texts of ENLIssue, that allows to add a subscriber and do whatever customization you feel like.
this will also make it easier to achieve custom salutations as proposed in https://github.com/collective/Products.EasyNewsletter/issues/58 (closing this)

we'll use http://jinja.pocoo.org/docs/dev/api/#high-level-api for the syntax to not invent something new here and to have a simple but powerful solution

**Comment by agitator** [comment]
solved with https://github.com/collective/Products.EasyNewsletter/pull/79
