### ISSUE TITLE
MultipartConversionError: Cannot attach additional subparts to non-multipart/* 

### ISSUE THREAD

**Issue by WouterVH** [collective/Products.EasyNewsletter#8]
r246619 from collective-svn, released in v2.6.1 throws this traceback:

Traceback (innermost last):
  Module ZPublisher.Publish, line 119, in publish
  Module ZPublisher.mapply, line 88, in mapply
  Module Products.PDBDebugMode.runcall, line 70, in pdb_runcall
  Module ZPublisher.Publish, line 42, in call_object
  Module Products.EasyNewsletter.browser.issue, line 23, in send_issue
  Module Products.EasyNewsletter.content.ENLIssue, line 412, in send
  Module email.MIMENonMultipart, line 21, in attach
MultipartConversionError: Cannot attach additional subparts to non-multipart/*

**Comment by jensens** [comment]
its always MIMEMultipart these days, so this is not valid on master.
