### ISSUE TITLE
Sent newsletter issues are not visible to anonymous viewers in 3.X

### ISSUE THREAD

**Issue by fredvd** [collective/Products.EasyNewsletter#82]
@benniboy @jensens was it a deliberate choice to change the permissions on Newsletter issues (enl_issue_workflow)  in https://github.com/collective/Products.EasyNewsletter/commit/a50485d2d16f2314b55d604a8176dc26f0f01be5 in the major cleanup?

In the sent state the default permissions no long acquire from the newsletter and are now visible only for Manager Owner and Editor, hence making them invisible for anonymouse viewers. This changes the behaviour from 2.X. and breaks sites where people upgrade.

**Comment by jensens** [comment]
Intention was to not be able to view drafts and masters. But 
see https://github.com/collective/Products.EasyNewsletter/commit/a50485d2d16f2314b55d604a8176dc26f0f01be5#diff-c2d094edd9bc742af4b5d39c8f7eb30aR66
is wrong anyway. 

So View in sent state should be acquired or set explicit to Viewer role?

 @MrTango @agitator what do you think?

**Comment by fredvd** [comment]
My quick fix in production now is to add acquire back to "view" and "Access contents information" and run update security settings. 

I fired up the old Plone 3 instance with easynewsletter 2.6.14 just to inspect what the old settings were, those are "acquire" for all the 5 managed permisions in the workflow and nothing else. So it falls back o (default) on the Newsletter, if the newsletter object is accessible so are its Issues.

**Comment by agitator** [comment]
i think the container state should give the permissions for sent issues

+1 for aquired

**Comment by jensens** [comment]
fixed by @agitator on master at  30 Mar 2016 (3 commits)
