### ISSUE TITLE
easynewsletter sending issue workflow does not protect against double sending

### ISSUE THREAD

**Issue by fredvd** [collective/Products.EasyNewsletter#83]
Recently we had another double EasyNewsletter sending issue.  Fortunately our MailHost was configured for queued sending, so allthough EasyNewsletters sent twice the messages, only the mails from the succesfull transaction were actually pushed out. 

We've been here before with other mailinglist set ups and @mauritsvanrees  added a failsafe there by setting a variable and doing a transaction.commit before continuing the send. Easynewsletter has something similar now with the workflow state. There are in issue.py two methods send_issue and _send_issue_prepare, but if zamqp is not installed this will now not prevent resending the newsletter.

if _send_issue_prepare would do a transaction.commit() after changing the workflow state to 'sending' we think the send_issue_immediately would also benefit Now the current (first) transaction will see the workflow state changed, but a second incoming request will still continue as well because the state for that request is still draft. 

Any flaws in logic here?  I think only @jensens mainly worked on the new two step code, maybe @agitator as well? @MrTango ?

**Comment by jensens** [comment]
I usually do not like transaction commits in the middle of a request, but well, yes, this will help. If the others are +1 on this please make a pull request.

If you need to be sure to have no doubles I'd propose to use the asynchronous approach. This helps also to not block a thread with a long running request and gives more control over the sendout.
