### ISSUE TITLE
3.0beta: What's holding us back from creating release on pypi?

### ISSUE THREAD

**Issue by fredvd** [collective/Products.EasyNewsletter#85]
See https://github.com/collective/Products.EasyNewsletter/commit/e4bc721b06be721eec59469eb6f9df496158bd37

Most of us are using 3.0 internally in production use but we're all afraid to release current master as a 'beta' in the wild, right?  @agitator @jensens @pbauer @MrTango 

Are there real blockers for pushing a beta 3.0 to pypi?

**Comment by MrTango** [comment]
The last status i know was, that we need to fix some tests, to run on Plone 5 and Plone 4.
I'll spend some time in the next two months, because I'll use ENL for a project, if no-one did the release before I will do that.

**Comment by jensens** [comment]
#89 and #90 should be solved.

**Comment by jensens** [comment]
#56 needs a check as well.

**Comment by agitator** [comment]
I also have a project for the next months, where I wan't to test and fix more stuff - @jensens already got some tasks ;-)

**Comment by jensens** [comment]
also #91

**Comment by MrTango** [comment]
I'll working on it soon too. Maybe we should talk, to coordinate the work.

**Comment by agitator** [comment]
https://github.com/collective/Products.EasyNewsletter/issues/88 too?

**Comment by MrTango** [comment]
yes I'm on this too ;)
This is fixed already, I'll push this soon.

**Comment by MrTango** [comment]
Test are passing now, but we still have some important things to fix, before the release.
The collection functionality is currently broken and the docs, tests as well as the rendering templates need some work. I have a bit budget for some of the work, but if anybody has some budget for this release, it would help a lot to get things done in time.

The plan is, to switch to the new collections. We will allow to reference one or more collections and maybe even other content. These will be rendered like the full_content_view for the content aggregation in the Newsletter. We will also add some new email templates, probably based on https://github.com/mailchimp/email-blueprints
