### ISSUE TITLE
[Plone 5] Get rid of zope.formlib

### ISSUE THREAD

**Issue by jensens** [collective/Products.EasyNewsletter#88]
Used in ``subscriber.py`` (also other places?), dependency in ``setup.py``. 

Background: ``zope.formlib`` is no longer part of Plone.

**Comment by MrTango** [comment]
removed for > Plone 4

**Comment by idgserpro** [comment]
There's still a reference to this package as a dependency in https://github.com/collective/Products.EasyNewsletter/blob/7f9e5bbe18ee5a41e83d056e8381a61438eda6c7/setup.py#L41

**Comment by MrTango** [comment]
thx, PR welcome, I'll not have the time until end of June
