### ISSUE TITLE
Can't create an issue in Plone 5.0.7

### ISSUE THREAD

**Issue by rafaeltcc** [collective/Products.EasyNewsletter#99]
Hi,

Is Products.EasyNewsletter 2.6.15 working in Plone 5.0. Or must I clone de repository in github?

My installation went ok, but trying to add an issue returns this error:

2017-04-28 03:44:43 ERROR Zope.SiteErrorLog 1493343883.810.350519218969 https://inverta.org/jornal/repositorio/correio-inverta/greve-geral-derrubar-o-golpe-e-o-circulo-de-mentiras-1/@@enl_public_view
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.Five.browser.metaconfigure, line 485, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 98, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 261, in render
  Module chameleon.template, line 191, in render
  Module chameleon.template, line 171, in render
  Module 1feb7ab72a965cc145ca200069d3838a.py, line 249, in render
  Module d981d461e75d1d3e318d4767dc544148.py, line 1223, in render_master
  Module d981d461e75d1d3e318d4767dc544148.py, line 458, in render_content
  Module 1feb7ab72a965cc145ca200069d3838a.py, line 191, in __fill_main
  Module five.pt.expressions, line 161, in __call__
  Module Products.EasyNewsletter.browser.issue, line 31, in get_public_body
  Module Products.EasyNewsletter.content.ENLIssue, line 310, in _render_output_html
  Module Products.EasyNewsletter.utils, line 16, in safe_portal_encoding
TypeError: encode() argument 1 must be string, not None

 - Expression: "view/get_public_body"
 - Filename:   ... egg/Products/EasyNewsletter/browser/issue_public_view.pt
 - Location:   (line 23: col 39)
 - Source:     tal:content="structure view/get_public_body"
                                      ^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7f20e2c367d0>
               views: <ViewMapper - at 0x7f20e323f610>
               modules: <instance - at 0x7f20fd3cc7e8>
               args: <tuple - at 0x7f2107b2e050>
               here: <ImplicitAcquisitionWrapper greve-geral-derrubar-o-golpe-e-o-circulo-de-mentiras-1 at 0x7f20e385bf00>
               user: <ImplicitAcquisitionWrapper - at 0x7f20e385b3c0>
               nothing: <NoneType - at 0x7ac030>
               container: <ImplicitAcquisitionWrapper greve-geral-derrubar-o-golpe-e-o-circulo-de-mentiras-1 at 0x7f20e385bf00>
               request: <instance - at 0x7f20e3289dd0>
               wrapped_repeat: <SafeMapping - at 0x7f20e37a2e68>
               traverse_subpath: <list - at 0x7f20e2aa56c8>
               default: <object - at 0x7f2107b04c50>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper greve-geral-derrubar-o-golpe-e-o-circulo-de-mentiras-1 at 0x7f20e385bf00>
               view: <SimpleViewClass from /home/rc/Plone-inverta/buildout-cache/eggs/Products.EasyNewsletter-2.6.15-py2.7.egg/Products/EasyNewsletter/browser/issue_public_view.pt enl_public_view at 0x7f20e323fb10>
               translate: <function translate at 0x7f20e3916e60>
               root: <ImplicitAcquisitionWrapper Zope at 0x7f20ec20b910>
               options: {...} (0)
               target_language: <NoneType - at 0x7ac030>
^C2017-04-28 03:49:26 INFO SignalHandler Caught signal SIGINT

Thanks

**Comment by rafaeltcc** [comment]
I forgot to teel I get this warning:

![image](https://cloud.githubusercontent.com/assets/3977779/25511307/5dd62668-2b9c-11e7-8236-4360922a573b.png)

**Comment by rafaeltcc** [comment]
Sorry, now I see I should be using 3 alpha. Can someone point me documentation or give me instructions to install it in a production env?

Thanks,

Rafael

**Comment by MrTango** [comment]
I'll release the 3.0Beta soon, please wait a bit or use the plone5_collection_support branch.
